// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2877.AerialAssist2014Robot;

import com.sun.squawk.microedition.io.FileConnection;
import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import java.io.DataInputStream;
import javax.microedition.io.Connector;
import org.usfirst.frc2877.AerialAssist2014Robot.commands.*;
import org.usfirst.frc2877.AerialAssist2014Robot.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command autonomousCommand;

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DriveTrain driveTrain;
    public static ShooterSubsys shooter;
    public static PickupArmSubsys pickup;
    public static RollerSubsys rollerSubsys;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Drive drive;
    public static SecondaryArmSubsys secondary;
    public static Roller roller;
    public static SmashboardCommand smashboardCommand;
    public static boolean pickupIsOpen = false;
    public static boolean secondaryIsOpen = false;
    public static boolean shooterIsPressurized = false;
    public static final double SHOOTER_CYLINDER_VOLUME = 21;
    public static final double SHOOTER_TANKS_VOLUME = 15;
    public static final double TRIGGER_VOLUME = 7.068;
    public static final double SECONDARY_VOLUME = 3.534;
    public static final double PICKUP_VOLUME = 5.301;
    public static final int NUMBER_TANKS = 11;
    public static final int TANK_VOLUME = 44;
    public static final int PRESSURE_MAX = 115;
    public static final int MAX_VOLUME = NUMBER_TANKS * TANK_VOLUME;
    public static final double MAX_MOLES = molesOfAir(MAX_VOLUME);
    public static double currentMoles;
    public static final String OVERSHOOT_FILE = "file:///overshoot_angle.txt";
    public static double OVERSHOOT_ANGLE = 15.0;

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
        RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrain = new DriveTrain();
        shooter = new ShooterSubsys();
        pickup = new PickupArmSubsys();
        rollerSubsys = new RollerSubsys();
        drive = new Drive();
        secondary = new SecondaryArmSubsys();
        roller = new Roller();
        smashboardCommand = new SmashboardCommand();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // This MUST be here. If the OI creates Commands (which it very likely
        // will), constructing it during the construction of CommandBase (from
        // which commands extend), subsystems are not guaranteed to be
        // yet. Thus, their requires() statements may grab null pointers. Bad
        // news. Don't move it.
        currentMoles = MAX_MOLES;
//        pneumaticCompressorTemporary = new PneumaticCompressorTemporary(20);
        oi = new OI();

        // instantiate the command used for the autonomous period
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        autonomousCommand = new AutonomousCommand();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
    }

    public static double molesOfAir(double volume) {
        double atm = 60.0 / 14.6959488;
        double liters = volume * 0.0163871;
        double moles = (atm * volume) / (0.0821 * 298);
        return moles;
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
        if (autonomousCommand != null) {
            autonomousCommand.start();
            SmartDashboard.putNumber("OVERSHOOT_ANGLE", OVERSHOOT_ANGLE);
        }
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
        RobotMap.jags.UpdateDashboard();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to 
        // continue until interrupted by another command, remove
        // this line or comment it out.
        System.out.println("teleopInit");
        if (autonomousCommand != null) {
            autonomousCommand.cancel();
        }
        drive.start();
        smashboardCommand.start();
        roller.start();
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        RobotMap.jags.UpdateDashboard();
        SmartDashboard.putNumber("OVERSHOOT_ANGLE", OVERSHOOT_ANGLE);
    }

    /**
     * This function called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
    public boolean readOvershoot() {
        try {
            // Persist our overshoot numbers to a file
            DataInputStream file;
            FileConnection fc;

            fc = (FileConnection)Connector.open(OVERSHOOT_FILE, Connector.READ);
            if (fc.exists()) {
                file = fc.openDataInputStream();
                System.out.println("Loading " + OVERSHOOT_FILE);
                OVERSHOOT_ANGLE = file.readDouble(); //override the default angle with this angle
                System.out.println(OVERSHOOT_ANGLE);

                file.close();
                fc.close();
            }
            else { System.out.println("No " + OVERSHOOT_FILE); }
        }
        catch (Exception ex) {
            System.out.println("File output error: " + ex.getMessage());
        }


        return true;
    }

}
