// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2877.AerialAssist2014Robot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
import org.usfirst.frc2877.AerialAssist2014Robot.subsystems.CANJags;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar driveTrainLeftFrontJag;
    public static CANJaguar driveTrainLeftRearJag;
    public static CANJaguar driveTrainRightFrontJag;
    public static CANJaguar driveTrainRightRearJag;
    public static RobotDrive driveTrainRobotDrive41;
    public static Gyro driveTrainGyro;
    public static DoubleSolenoid shooterSolenoidShoot;
    public static DoubleSolenoid shooterKickerSolenoid;
    public static CANJaguar pickupRollerJag;
    public static DoubleSolenoid pickupPickupSolenoid;
    public static DoubleSolenoid pickupSecondarySolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Compressor pneumaticPusherPushCompressor;
    public static final int JAGUAR_COUNT = 5;
    public static CANJags jags = new CANJags(JAGUAR_COUNT);
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFrontJag = jags.init(2, "driveTrainLeftFrontJag");
        driveTrainLeftRearJag = jags.init(3, "driveTrainLeftRearJag");
        driveTrainRightFrontJag = jags.init(5, "driveTrainRightFrontJag");
        driveTrainRightRearJag = jags.init(6, "driveTrainRightRearJag");
        pickupRollerJag = jags.init(4, "pickupRollerJag");
                        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFrontJag, driveTrainLeftRearJag,
              driveTrainRightFrontJag, driveTrainRightRearJag);
	
        driveTrainRobotDrive41.setSafetyEnabled(false);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);

        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveTrainGyro = new Gyro(1);
	LiveWindow.addSensor("DriveTrain", "Gyro", driveTrainGyro);
        driveTrainGyro.setSensitivity(0.007);	
        
        shooterSolenoidShoot = new DoubleSolenoid(6, 5);
        shooterKickerSolenoid = new DoubleSolenoid(7, 8);      
	
        pickupPickupSolenoid = new DoubleSolenoid(4, 3);      
        pickupSecondarySolenoid = new DoubleSolenoid(2, 1);      
	
        pneumaticPusherPushCompressor = new Compressor(1, 1);
        pneumaticPusherPushCompressor.start(); 
        System.out.println("Compressor Started");
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
